title: My Personal Homepage
baseurl: "" # 如果部署到子目录，可以设置为子目录的路径，如 "/mywebsite"
# url: "http://localhost:4000" # 本地或最终部署的URL
# theme: jekyll-theme-slate # 或其他你喜欢的主题
collections:
  pages:
    output: true
